[package]
name = "typokat-frontend"
version.workspace = true
edition.workspace = true

[features]
test-utils = []

[dependencies]
jsonc-parser.workspace = true
oxc_allocator.workspace = true
oxc_ast.workspace = true
oxc_parser.workspace = true
oxc_resolver.workspace = true
oxc_span.workspace = true
typokat-binder.workspace = true
typokat-core.workspace = true
typokat-types.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
